list = []
l1 = input("Enter 1st fruit name : ")
list.append(l1) 
l2 = input("Enter 2nd fruit name : ")
list.append(l2)
l3 = input("Enter 3rd fruit name : ")
list.append(l3)
l4 = input("Enter 4th fruit name : ")
list.append(l4)
l5 = input("Enter 5th fruit name : ")
list.append(l5)
l6 = input("Enter 6th fruit name : ")
list.append(l6)
l7 = input("Enter 7th fruit name : ")
list.append(l7)

print(list)