marks = []
l1 = int(input("Enter 1st subject marks : "))
marks.append(l1) 
l2 = int(input("Enter 2nd subject marks : "))
marks.append(l2)
l3 = int(input("Enter 3rd subject marks : "))
marks.append(l3)
l4 = int(input("Enter 4th subject marks : "))
marks.append(l4)
l5 = int(input("Enter 5th subject marks : "))
marks.append(l5)
l6 = int(input("Enter 6th subject marks : "))
marks.append(l6)

marks.sort()
print(marks)